# Generated by Django 5.0.3 on 2024-03-26 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookappointment',
            name='time_interval',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
