# Generated by Django 5.0.3 on 2024-03-28 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_bookappointment_time_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookappointment',
            name='gmeet_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
