# Generated by Django 5.0.3 on 2024-03-29 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_bookappointment_gmeet_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookappointment',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
